### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by austinhuang0131**
* Haversine distance is now built into the app instead of requiring your JAR file. First, F-Droid does not allow pre-built JARs, so #22 requires it to be removed. Second, you don't need an entire library just to calculate distance between points. Finally, if you do need to require it, you can use [JitPack](https://jitpack.io) to require [a GitHub repo](https://github.com/paleolimbot/java-geo) on Gradle.
* Add an AlertDialog to tell people when a radar is out, since there are confused users on Google Play reviews...
* Fastlane structure. Again, for #22, but I think Google Play can also accept Fastlane.
* Sort locations by distance when GPS is used
* Use the new radar map link for "View online"
* Update radar sites and some other UI stuff

Let me know if you want me to submit a request to F-Droid, after you merge this.

### CODE REVIEW

**Comment by austinhuang0131** [comment]
Bumping this

**Comment by ramzan** [comment]
You could just submit your fork to F-Droid, since this app appears to be abandoned.

**Comment by austinhuang0131** [comment]
I guess @izzysoft can answer this, but the maintainer himself is still alive, just not responding to any emails (`dewey@fishandwhistle.net` on his webite) regarding the app (I think Google Play reviews indicated that too, therefore I'm not alone), so it might not be considered "abandoned"

I mean I see the maintainer has another email address in GitHub commits but like I kinda don't want to resort to extreme measures unnecessarily

**Comment by austinhuang0131** [comment]
> This code is GPL...is there any reason you haven't stolen the parts you like and just created a new app?

GPLv2 (like GPLv3) requires me to open source the app and preserve license

Well I mean I can take over the project and continue it as necessary (and you can still publish it in your name, just credit me inside, while I publish it on F-Droid), ~~after all my previous project got axed and I need a new one anyway~~. As for intention, this PR should prove that my intention is genuine.

**Comment by austinhuang0131** [comment]
Oh well. I'm more maintaining it for practice (furthering my coding skill as well as resume material) and for fun (what covid boredom does to people), so I guess I'll take it if the following proposal is acceptable to you:

* Either I continue working in this repo (collaborator access or PR) or I start a fork.
  * If we go with the former, you (being the sole previous contributor) should change the license of the fork to [GPLv3 or later](https://spdx.org/licenses/GPL-3.0-or-later.html). This is for license compatibility with third-party dependencies (like Retrofit). Both of our credits would be on it, you first (earlier), then me.
  * If we go with the latter, then you should provide me a waiver to change the license in a similar fashion. Your original license would still be GPLv2, and I will show your credit and the waiver in the app.
* You continue to publish the app on Google Play with your key for the purpose of continuity (credit me as you see fit). I publish the app on F-Droid with F-Droid's key. I think not a lot of people download from GitHub so key selection here does not matter much in my opinion.
* I will discontinue Android 4.x support as soon as possible (due to component deprecation).
* I will contribute on my free time (like weekends, probably) and may bring in additional contributors over the course.

**Pull request closed without merging**
